### ISSUE TITLE
Add `pid-cwd` to related section

### ISSUE THREAD

**Issue by NeekSandhu** [sindresorhus/pid-port#7]
I'm the author of [`pid-cwd`](https://www.npmjs.com/package/pid-cwd), a cross-platform library to find the directory where a process was started.

I think if these packages are cross-referenced, it will enhance the process for people building things like [`ultra-runner`](https://www.npmjs.com/package/ultra-runner) _(uses `pid-cwd` to show `Project` column)_

You can close the issue to reject.

**Comment by sindresorhus** [comment]
Sure, PR welcome.
